import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import ProvidersLayout from './providersLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        <main className='px-8 py-20 max-w-6xl mx-auto'>
          <ProvidersLayout>{children}</ProvidersLayout>
        </main>
      </body>
    </html>
  )
}
